# Generated by Django 5.1.6 on 2025-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('application_date', models.DateField(auto_now=True)),
                ('job_type', models.CharField(choices=[('hybrid', 'hybrid'), ('remote', 'remote'), ('on_site', 'on_site')], max_length=10)),
            ],
        ),
    ]
