# Generated by Django 5.1.6 on 2025-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userapplications_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplications',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
