# Generated by Django 5.1.6 on 2025-03-09 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userapplications_applied_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('application_date', models.DateField(auto_now=True)),
                ('job_type', models.CharField(choices=[('hybrid', 'hybrid'), ('remote', 'remote'), ('on_site', 'on site'), ('in_person', 'in person')], max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserApplications',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='main_app.user'),
        ),
    ]
